import type { Metadata } from "next";
import "../styles/globals.css";
import {Noto_Sans} from "next/font/google";


const notoSans = Noto_Sans({
	subsets: ["latin"],
	display: "swap",
	weight: ["300","400", "500","700"],
});


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};


export default function RootLayout({
	children,
	}: Readonly<{
	children: React.ReactNode;
	}>) {
return (
	<html lang="en" className={`${notoSans.className}`}>
		<body>
			{children}
		</body>
	</html>
);
}
